version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      backend:
        ipv4_address: 10.5.0.2
    links:
      - minio:minio.hm22.local
    volumes:
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

  minio:
    container_name: minio
    image: minio/minio:latest
    command: minio server /data --console-address "0.0.0.0:9001" --certs-dir /certs
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      backend:
        ipv4_address: 10.5.0.3
    volumes:
      - ./data/minio:/data
      - ./data/caddy/data/caddy/pki/authorities/local/root.crt:/certs/CAs/root.crt
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=https://console.minio.hm22.local
      - MINIO_SERVER_URL=https://minio.hm22.local
    extra_hosts:
      - minio.hm22.local:10.5.0.2

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 10.5.0.4
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001/udp"
      - "4001:4001"
    volumes:
      - ./data/ipfs/export:/export
      - ./data/ipfs/storage:/data/ipfs

  create-static:
    container_name: create-static
    image: minio/mc:latest
    entrypoint: /bin/bash
    command: ./create.sh
    volumes:
      - ./create.sh:/create.sh

  build-static:
    container_name: build-static
    image: node:16
    command: ./build.sh
    volumes:
      - ./build.sh:/build.sh
      - ./static:/static

  push-static:
    container_name: push-static
    image: minio/mc:latest
    command: cp --insecure -r /static/dist/ minio/static
    networks:
      backend:
        ipv4_address: 10.5.0.20
    volumes:
      - ./static:/static
      - ./data/mc:/root/.mc
      - ./data/caddy/data/caddy/pki/authorities/local/root.crt:/certs/CAs/root.crt
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MC_HOST_minio=https://${MINIO_ACCESS_KEY}:${MINIO_SECRET_KEY}@minio.hm22.local
    extra_hosts:
      - minio.hm22.local:10.5.0.2

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 10.5.0.5

  api:
    image: node:16
    command: /app/bin/www
    networks:
      backend:
        ipv4_address: 10.5.0.8
    volumes:
      - ./node_modules:/app/node_modules
      - ./bin/www:/app/bin/www

  worker:
    image: node:16
    command: /app/bin/worker
    networks:
      backend:
        ipv4_address: 10.5.0.7
    volumes:
      - ./node_modules:/app/node_modules
      - ./bin/worker:/app/bin/worker
    environment:
      - REDIS_HOST=redis

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
